services:
  db:
    image: postgres:17
    container_name: vtlink-db
    environment:
      POSTGRES_DB: vtlink_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - vtlink_network

  redis:
    image: redis:7-alpine
    container_name: vtlink-redis
    ports:
      - 6379:6379
    networks:
      - vtlink_network

networks:
  vtlink_network:
    driver: bridge

volumes:
  db_data:
    driver: local
