name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version-file: go-backend/go.mod
          cache-dependency-path: go-backend/go.sum

      - name: Install tools
        working-directory: ./go-backend
        run: make install-tools

      - name: Generate code
        working-directory: ./go-backend
        run: make generate

      - name: Check formatting
        working-directory: ./go-backend
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Code not formatted. Run 'make fmt'"
            exit 1
          fi

      - name: Run lint
        working-directory: ./go-backend
        run: make lint

      - name: Run tests
        working-directory: ./go-backend
        run: make test

      - name: Build
        working-directory: ./go-backend
        run: make build